categories_map = {'Anatomy': 'IGN',
                  'Anniversary': 'IGN',
                  'Automobile': 'BUY',
                  'City': 'GEO',
                  'Company': 'INFO',
                  'Continent': 'GEO',
                  'Country': 'GEO',
                  'Crime': 'IGN',
                  'Degree': 'IGN',
                  'Drug': 'IGN',
                  'EntertainmentAward': 'INFO',
                  'Facility': 'INFO',
                  'FieldTerminology': 'INFO',
                  'FinancialMarketIndex': 'INFO',
                  'GeographicFeature': 'INFO',
                  'HealthCondition': 'INFO',
                  'Holiday': 'INFO',
                  'JobTitle': 'INFO',
                  'Movie': 'MOVIE',
                  'MusicGroup': 'MUSIC',
                  'NaturalDisaster': 'INFO',
                  'OperatingSystem': 'INFO',
                  'Organization': 'INFO',
                  'Person': 'PER',
                  'PrintMedia': 'IGN',
                  'Product': 'BUY',
                  'ProfessionalDegree': 'INFO',
                  'RadioProgram': 'INFO',
                  'RadioStation': 'INFO',
                  'Region': 'GEO',
                  'Sport': 'INFO',
                  'SportingEvent': 'INFO',
                  'StateOrCounty': 'GEO',
                  'Technology': 'INFO',
                  'TelevisionShow': 'TV',
                  'TelevisionStation': 'TV',
                  'EmailAddress': 'IGN',
                  'TwitterHandle': 'IGN',
                  'Hashtag': 'ING',
                  'IPAddress': 'IGN',
                  'Quantity': 'IGN',
                  'Money': 'IGN'}

def match_category(cat):
    if cat in categories_map:
        return categories_map[cat]
    else:
        return 'IGN'